/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as AdminResetPasswordRouteImport } from './routes/admin_.reset-password'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin_.forgot-password'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRoute,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/admin_/reset-password',
  path: '/admin/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/admin_/forgot-password',
  path: '/admin/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRouteWithChildren
  '/quote': typeof QuoteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRouteWithChildren
  '/quote': typeof QuoteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRouteWithChildren
  '/quote': typeof QuoteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin_/forgot-password': typeof AdminForgotPasswordRoute
  '/admin_/login': typeof AdminLoginRoute
  '/admin_/reset-password': typeof AdminResetPasswordRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/products'
    | '/quote'
    | '/sitemap.xml'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/reset-password'
    | '/products/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/products'
    | '/quote'
    | '/sitemap.xml'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/reset-password'
    | '/products/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/products'
    | '/quote'
    | '/sitemap.xml'
    | '/admin_/forgot-password'
    | '/admin_/login'
    | '/admin_/reset-password'
    | '/products/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  QuoteRoute: typeof QuoteRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/admin_/reset-password': {
      id: '/admin_/reset-password'
      path: '/admin/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/forgot-password': {
      id: '/admin_/forgot-password'
      path: '/admin/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProductsRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsSlugRoute: ProductsSlugRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ProductsRoute: ProductsRouteWithChildren,
  QuoteRoute: QuoteRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
